### ISSUE TITLE
Training procedure of Kangaroo.

### ISSUE THREAD

**Issue by tim-pan** [Equationliu/Kangaroo#2]
Hi Equationliu and all authors, 
Thanks for your brilliant work in proposing this promising "Kangaroo" method.
I am curious about training details of Kangaroo. Could you plz provide the training code of Kangaroo~~?  
Thanks in advance.

**Comment by yangfuwei** [comment]
+1, looking forward your training code. Thanks.

**Comment by Equationliu** [comment]
Thanks for your interest. We will release our training code soon.

**Comment by shiyuetianqiang** [comment]
+1, looking forward your training code. Thanks.

**Comment by oyy2000** [comment]
+1, very very excited about the whole project!

**Comment by Equationliu** [comment]
We have released our training code for Kangaroo, thanks for all your interest. :heart::heart:
