### ISSUE TITLE
In line 263 of train.py， predict = model(inputs_embeds=data["hidden_states_early"]

### ISSUE THREAD

**Issue by cool-xiang** [Equationliu/Kangaroo#3]
Hello author! Thank you for your excellent work!

In line 263 of train.py， predict = model(inputs_embeds=data["hidden_states_early"], attention_mask=data["attention_mask"])，
report error "model has no attribute inputs.embeds"  
because the class AdapterModel in adapter.py does not define a forward(), only the forward_early_stop()
Can you add a forward()?

**Comment by Equationliu** [comment]
Thank you for pointing out this issue. We have fixed it.
