### ISSUE TITLE
Kangaroo when bsz is greater than 1.

### ISSUE THREAD

**Issue by cool-xiang** [Equationliu/Kangaroo#6]
Hello, I would like to ask how Kangaroo works in scenarios where bsz is greater than 1, and which parts of the code need to be modified. Thank you!

**Comment by Equationliu** [comment]
The current version does not support batch decoding. Compared with other methods, kangaroo has to process the dynamic step size in the drafting process in addition to different samples are not synchronized along the batch dimension.

**Comment by cool-xiang** [comment]
ok, thank you!
